ENU/55349AC/Labs/Mod01/0101-Plan an IPv4 addressing scheme.md

Hi Conan,
I've completed my edit pass to the Mod 1 LAK. Please let me know if there's another way you'd like me to do this. Otherwise, you can view my changes in the diff.
Thanks,
Dallas

PR for CE of Update 0101-Plan an IPv4 addressing scheme.md

---

ENU/55349AC/Labs/Mod02/0201-Implement DHCP.md

Hi Conan,
I've completed my edit pass for 55349AC Mod 2's LAK, "Implement DHCP". Please note, I modified steps on lines 236, 273, 321, 329, and 337 to make two sentences out of one. Otherwise, general comments. 
Thanks,
Dallas

Update 0201-Implement DHCP.md

---

ENU/55349AC/Labs/Mod03/0301-Configure and evaluate IPv6 transition technologies.md

Hi Conan,
I've completed my edit pass. A couple of changes where I made two sentences out of one, but those should show up in the diff file.
Thanks,
Dallas

Update 0301-Configure and evaluate IPv6 transition technologies.md

---

ENU/55349AC/Labs/Mod04/0401-Plan and implement DNS name resolution.md

Hi Conan,
I've completed my edit pass. Let me know if you have any concerns.
Thanks,
Dallas

Update 0401-Plan and implement DNS name resolution.md

---

ENU/55349AC/Labs/Mod04/0402-Integrate DNS with AD DS.md

Hi Conan,
This is my last one for today. I've completed my edit pass. I'll finish the rest up tomorrow (Thursday).
Cheers,
Dallas

Update 0402-Integrate DNS with AD DS.md

---

ENU/55349AC/Labs/Mod06/0602-Implement a VPN.md

Hi @ckezema 
I've completed my edit pass for this one. A couple comments:
• There are instances of double-click. Fix as applicable if you can, otherwise OK.
• Line 313: I think the statement should not be part of the table. If you agree, can you fix?
• Line 353: the sentence references "commands" but then there's only one command that's included. Should there be more? If so, can you add them. If not, can you change the lead-in sentence?
• Line 422: You refer to "Logan" now being able to connect to the Contoso VPN but the "scenario memo" references "Tonnie"?!
Thanks,
Dallas

Update 0602-Implement a VPN.md

---

ENU/55349AC/Labs/Mod06/0601-Implement a Web Application Proxy.md

Hi Conan,
I've completed my edit pass. Please notice on line 134, I broke one sentence into two sentences. And on line 244, there's an instance of "double-click". I've mentioned this in other LAK PRs. If there's a way to address people not using a mouse, let's add it.
Thanks,
Dallas

Update 0601-Implement a Web Application Proxy.md

---

ENU/55349AC/Labs/Mod05/0501-Implement IPAM.md

Hi Conan,
I've completed my edit pass for this one. Could you check out line 87, where I spelled out the full terms to introduce three acronyms, and then line 168, where we use "double-click". Was wondering if there's another way for a student not using a mouse to perform that step. 
Cheers,
Dallas

Update 0501-Implement IPAM.md

---

ENU/55349AC/Labs/Mod07/0701-Implement DFS for branch offices.md

Hi @ckezema 
I've completed my edit pass. My only comment is in the lab title, line 1, we use "DNS" but we don't typically spell out acronyms in titles. It's not used anywhere else. Do you think that'll be confusing for users or will they be OK knowing it's short for "Domain Name System"?
Thanks,
Dallas

Update 0701-Implement DFS for branch offices.md

---

ENU/55349AC/Labs/Mod08/0801-Configure advanced Hyper-V networking features.md

Hi @ckezema 
I've completed my edit pass for this one. Please note, I made two sentences out of the original "one" on line 216, but otherwise, just basic editing stuff.
Thanks,
Dallas

Update 0801-Configure advanced Hyper-V networking features.md

---

ENU/55351AC/Labs/Mod02/0201-Manage AD DS objects.md

There are some changes for you to review, and then also:
• Lines 137 and 148: There's italic text that I can't get to switch to plain text. Can you fix it?
• Lines 203 and 204: In the .md content, both lines have the #1. But then when I review the preview file, the numbering is fine. Just calling it out.

CE complete for 0201-Manage AD DS objects.md

---

ENU/55351AC/Labs/Mod02/0202-Administer AD DS.md

A few changes for you to review and then one question -- on line 11, we use "helpdesk" but elsewhere, we use "help-desk" (with the hyphen). Can we make it consistent throughout? Thanks!

CE complete for 0202-Administer AD DS.md

---

ENU/55351AC/Labs/Mod01/0101-Deploy and administer AD DS.md

Hi @ckezema ,
I've completed my CE pass. You can review the changes in the PR. Also, one question for you. On line 91, should the words "at the end of each line" be plain text rather than bold?
Thanks,
Dallas

CE complete for 0101-Deploy and administer AD DS.md

---

ENU/55351AC/Labs/Mod03/0301-Domain and trust management in AD DS.md

A few minor changes for you to review. Thanks!

CE complete for 0301-Domain and trust management in AD DS.md

---

ENU/55351AC/Labs/Mod04/0401-Implement AD DS sites and replication.md

Hi @ckezema. I've completed my edit pass. Nothing major. Thanks!

CE complete for 0401-Implement AD DS sites and replication.md

---

ENU/55351AC/Labs/Mod05/0501-Implement a Group Policy infrastructure.md

Hi @ckezema. I've finished my edit pass. Nothing major. Thanks!

CE complete for 0501-Implement a Group Policy infrastructure.md

---

ENU/55351AC/Labs/Mod05/0502-Troubleshoot Group Policy infrastructure.md

Hi @ckezema. I've completed my edit pass. Minor changes. Thanks!

CE complete on 0502-Troubleshoot Group Policy infrastructure.md

---

ENU/55351AC/Labs/Mod06/0601-Manage user settings with Group Policy.md

Hi @ckezema. I've completed my edit pass and it's ready for you. Thanks!

CE complete for 0601-Manage user settings with Group Policy.md

---

ENU/55351AC/Labs/Mod09/0901-Deploy and use certificates.md

Hi @ckezema. I've completed my edit pass. Cheers!

CE complete on 0901-Deploy and use certificates.md

---

ENU/55351AC/Labs/Mod08/0801-Deploy and configure a two-tier CA hierarchy.md

Hi @ckezema. I've completed my edit pass. Thanks!

CE complete on 0801-Deploy and configure a two-tier CA hierarchy.md

---

ENU/55351AC/Labs/Mod10/1001-Implement AD FS.md

Hi @ckezema. I've completed my edit pass for 1001-Implement AD FS.md. Thanks! --Dallas

CE complete for 1001-Implement AD FS.md

---

ENU/55351AC/Labs/Mod11/1101-Configure directory synchronization.md

Hi @ckezema. I've completed my edit pass. Thanks!

CE complete on 1101-Configure directory synchronization.md

---

ENU/55351AC/Labs/Mod12/1201-Recover objects in AD DS.md

Hi @ckezema. I've completed my edit pass. And that's it for the 55351 labs. YAY! :-)

CE complete on 1201-Recover objects in AD DS.md

---

ENU/55356AC/Labs/Mod01/0101 - Use the SELECT statement to retrieve data from a database.md

…se.md
Hi @ckezema, I've completed my edit pass for 0101 - Use the SELECT statement to retrieve data from a database.md Thanks! --Liz

CE complete for 0101 - Use the SELECT statement to retrieve data from a database.md

---

ENU/55356AC/Labs/Mod03/0304 - Add and change data in SQL Server.md

Hi @ckezema I've completed the edit pass for 0304 - Add and change data in SQL Server.md. Thanks!--Liz
I have a couple of comments:
Lines 202, 204 not bolding correctly:
> Ensure the `emp_id` value matches the field in the row you added during **Task 1**.
3. Select the **Execute** button, or select **`F5`** on the keyboard to run the statement.

CE complete for 0304 - Add and change data in SQL Server.md

---

ENU/55367AC/Labs/Mod02/0201-Implement Identity Services and Group Policy.md

Hi @ckezema, I've completed the edit pass for 0201-Implement Identity Services and Group Policy.md.
No additional comments. Thanks! Liz

CE complete for 0201-Implement Identity Services and Group Policy.md

---

ENU/55367AC/Labs/Mod08/0801-Configure security in Windows Server.md

Hi @ckezema I've completed the edit pass for 0801-Configure security in Windows Server.md
I have a global comment for all files that I'll send to you by email. Let me know if you have any questions. Thanks! Liz

CE complete for 0801-Configure security in Windows Server.md

---

ENU/55367AC/Labs/Mod11/1101-Monitor and troubleshoot Windows Server.md

Hi @ckezema, I've completed the edit pass for 1101-Monitor and troubleshoot Windows Server.md
No comments on this lab. Thanks! Liz

CE complete for 1101-Monitor and troubleshoot Windows Server.md

---

ENU/55382AC/Labs/Mod01/0101-Deploy and configure Windows Server Core.md

Hi @ckezema, I've completed my edit pass of 20740 Lab 1, and it's ready for your review. Dallas said to put any questions/comments I have in here, so here goes:
Line 35 - I can't find a "Windows Server 2022 ISO. Does ISO stand for something? If so, please define it. Line 57 - Does the server management window have a name? Or should this be the "Windows Server management window?" Line 105 - Should this be "To exit the Command Prompt window?" According to Term Studio, we type at a command line in the Command Prompt window. Line 131 - I cannot find "Remote PowerShell" anywhere. I can find "Windows PowerShell remoting." Line 179 - We say they need to "repeat steps," but we don't say which steps they need to repeat. Lines 201 and 215 - Can we change these to "On the top menu, select the …

CE complete for 20740 Lab 1

---

ENU/55382AC/Labs/Mod02/0201-Manage disks and volumes in Windows Server.md

Hi @ckezema,
I've completed my edit pass of 0201-Manage disks and volumes in Windows Server.md, and it is ready for your review. In addition: Line 173. Can we change to "Notice the NTFS volume on **Disk 5** has a size of approximately **10** gigabytes (GB)."
Line 213: Can we change to "...for use in Microsoft Hyper-V running in Windows Server."

CE complete for 0201-Manage disks and volumes in Windows Server.md

---

ENU/55382AC/Labs/Mod03/0301-Plan and configure storage technologies and components.md

Hi @ckezema,
I've completed my review for this Mod 3 LAK, "Implementing enterprise storage solutions," and it's ready for your review. Comments are: Line 48: Can we change this to "...storage for Microsoft SQL Server databases?" If you agree to change, please search for the remaining "SQL database (or databases), and change to "SQL Server database/databases. Line 271. Instead of "at the message," can we say what the box or message are? Something more descriptive would be nice.
Line 401: Should Windows be Windows Server?

CE complete for Mod 3 LAK - Implementing enterprise storage solutions.md

---

ENU/55382AC/Labs/Mod04/0402-Implementing Data Deduplication.md

Hi @ckezema
I've completed my review of mod 4 Lab 4B, "Implementing Data Deduplication," and it's ready for your review. I only have one comment for you, as follows:
Line 89: Can we change this to "**Note:** Record the values returned from the previous command, as you will use them later in the lab?"

CE complete for Mod 4 Lab 4B, Implementing Data Deduplication

---

ENU/55382AC/Labs/Mod05/0501-Install and configure Hyper-V.md

Hi @ckezema,
I've completed the edits for the mod 5 LAK "Install and configure Hyper-V," and it's ready for your review. A few comments in here though:
Line 65: Can we change "...you should have successfully verified..." to "you successfully verified," or "you will have verified?"
Line 90: Can we give them a name for the drop-down menu? Someone who cannot see otherwise might not be able to find it unless it is intuitive.
Line 97: Where do they select Local Server from, in Server Manager?
Line 112: Can we change "...has been added. A private network..." to "...has been added, and that a private network...?" Otherwise, should the sentence beginning w/ "A private network" be changed to a Note?
Line 172: Can we change **New Virtual Machine** **Wizard** to **New Virtual Machine Wizard**? Same …

CE complete for Mod 5 LAK, Install and configure Hyper-V

---

ENU/55367AC/Labs/Mod06/0601-Implement_failover_clustering.md

Hi @ckezema,
I've completed my edit pass. I inserted two comments: line 329 and line 475. Hopefully, I used the correct markdown syntax. Please let me know if you have any questions.
Thanks,
Dallas

CE complete for 0601-Implement_failover_clustering.md

---

ENU/55367AC/Labs/Mod09/0901-Implement_RDS_in_Windows_Server.md

Hi @ckezema,
I've completed my edit pass for 0901-Implement_RDS_in_Windows_Server.md. I inserted comments on lines 59 and 79.
Let me know if you have any questions. Thanks!
Dallas

CE complete on 0901-Implement_RDS_in_Windows_Server.md

---

ENU/55367AC/Labs/Mod04/0401- Implementing Data Deduplication.md

Hi @ckezema. I've completed my CE pass on 0401- Implementing Data Deduplication.md. Thanks!

CE complete for 0401- Implementing Data Deduplication.md

---

ENU/55367AC/Labs/Mod04/0402- Configuring iSCSI storage.md

Hi @ckezema. I've completed my edit pass for 0402- Configuring iSCSI storage.md. Thanks! :-)

CE complete for 0402- Configuring iSCSI storage.md

---

ENU/55367AC/Labs/Mod04/0403- Configuring redundant storage spaces.md

Hi @ckezema. CE is done for 0403- Configuring redundant storage spaces.md. Thanks!

CE complete for 0403- Configuring redundant storage spaces.md

---

ENU/55367AC/Labs/Mod04/0404- Implementing Storage Spaces Direct.md

Hi @ckezema. I've completed my edit pass for 0404- Implementing Storage Spaces Direct.md. One question about some verbiage that you use several places, where you instruct them to "select line <xy>" or similar. Will that be intuitive for them? It's not for me, but that's probably because I'm not actually in the lab and UI. Just wanted to make sure. Thanks!

CE complete for 0404- Implementing Storage Spaces Direct.md

---

ENU/55367AC/Labs/Mod04/0401- Implementing Data Deduplication.md

Changed lab title to imperative rather than gerund. --Dallas

Update 0401- Implementing Data Deduplication.md

---

ENU/55367AC/Labs/Mod04/0402- Configuring iSCSI storage.md

Changed a couple titles to use imperatives rather than gerunds and one capitalization error.

Update 0402- Configuring iSCSI storage.md

---

ENU/55367AC/Labs/Mod04/0403- Configuring redundant storage spaces.md

Changed a couple titles to imperatives.

Update 0403- Configuring redundant storage spaces.md

---

ENU/55367AC/Labs/Mod04/0404- Implementing Storage Spaces Direct.md

Couple title changes to imperatives.

Update 0404- Implementing Storage Spaces Direct.md

---

ENU/55367AC/Labs/Mod07/0701-Implement Hyper-V Replica and Windows Server Backup.md

Update 0701-Implement Hyper-V Replica and Windows Server Backup.md

---

ENU/55367AC/Labs/Mod08/0801-Configure security in Windows Server.md

Update 0801-Configure security in Windows Server.md

---

ENU/55367AC/Labs/Mod10/1001-Deploy network workloads.md

Fixed some headings and "levels" for headings.

Update 1001-Deploy network workloads.md

---

ENU/55367AC/Labs/Mod11/1101-Monitor and troubleshoot Windows Server.md

Update 1101-Monitor and troubleshoot Windows Server.md

---

ENU/55367AC/Labs/Mod12/1201-Migrate server workloads.md

Hi @ckezema. I've completed my edit pass. There's a comment in there (hope I used the correct syntax) on line 85. Thanks!

CE complete for 1201-Migrate server workloads.md

---

ENU/55382AC/Labs/Mod06/0601- Install and configure containers.md

Hi @ckezema. I've completed my edit pass for 0601- Install and configure containers.md. Thanks!

CE complete for 0601- Install and configure containers.md

---

ENU/55382AC/Labs/Mod08/0802-Manage a failover cluster.md

Hi @ckezema. I've completed my edit pass for 0802-Manage a failover cluster.md. Thanks!

CE complete for 0802-Manage a failover cluster.md

---

ENU/55382AC/Labs/Mod08/0801-Implement a failover cluster.md

Hi @ckezema. I've completed my edit pass for this one. Thanks!

CE complete for 0801-Implement a failover cluster.md

---

ENU/55382AC/Labs/Mod09/0901-Implement failover clustering with Hyper-V.md

Hi @ckezema. I've completed my edit pass. There's a comment in the file at line174. Thanks!

CE complete for 0901-Implement failover clustering with Hyper-V.md

---

ENU/55382AC/Labs/Mod10/1001-Use MDT to deploy Windows Server.md

Hi @ckezema. I've finished my edit pass for 1001-Use MDT to deploy Windows Server.md. Thanks!

CE complete on 1001-Use MDT to deploy Windows Server.md

---

ENU/55382AC/Labs/Mod11/1101-Implement WSUS and deploy updates.md

Hi @ckezema. I've finished my edit pass for this one. Only one more. ;-) Cheers!

CE complete for 1101-Implement WSUS and deploy updates.md
